### ISSUE TITLE
Console writes out dates that are not valid, why?

### ISSUE THREAD

**Issue by jcorbs** [meghapabby/DataParsing#2]
When I run this on the marketing file, the console prints three valid dates:
![date_output](https://cloud.githubusercontent.com/assets/17605711/18369674/153f70e2-75dc-11e6-8579-79b3b1666f5a.png)
Two are invalid. Why is this?

**Comment by meghapabby** [comment]
The Console.WriteLine was outside the if conditional statement. Sorry, I missed adding { } for the if condition. I also made another small change in the TryParseExtract method. The format parameter was mmddyyyy, I changed it to MMddyyyy. I noticed that MM is the standard format for month format specifier

foreach (Match m in matches) 

```
         { 
            DateTime validDate; 
            if(DateTime.TryParseExact(m.Value,"MMddyyyy", null, DateTimeStyles.None, out validDate)) 
            { 
                if(validDate < today)       
                {
                OutputDates.Add(validDate); 
                Console.WriteLine("Valid date found: " + validDate.Date.ToString("d")); 
                }
            } 
        } 
```
