### ISSUE TITLE
Program Does Not Find All Valid Dates

### ISSUE THREAD

**Issue by jcorbs** [meghapabby/DataParsing#3]
Using your code to parse, only one valid date is returned: 01101997. There are more matches. A reason for this is your assumption that 1900 is the bottom end of the valid dates. That requirement was never stated.
1. Why did you assume that?
2. What would you do to change this apply to all dates in the past?

**Comment by meghapabby** [comment]
1. I assumed that there was no marketing data earlier than 01-01-1900. The requirement stated that I should specify any assumptions that I make.
2. I have created the regular expression to comply with my assumption
   string pattern = @"(?<OutputDate>(0[1-9]|[10-12])(0[1-9]|[12][0-9]|3[01])(19|20)\d\d)";

To change it to apply to all dates, I would use the following regular expression
string pattern = @"(?<OutputDate>(0[1-9]|[10-12])(0[1-9]|[12][0-9]|3[01])(1[0-9]|20)\d\d)";
this would allow dates between the year 1000-2099.
For doing the check to make sure we only get past dates, I have an if condition to compare the valid date with today's date on line 34.

If we want to allow a date further than 2099, I would modify the last part of the expression to
 ([1-9][0-9])\d\d).

Hope this answers your questions.

Thanks!
